We will cal you
guemplen/project-team-3 pull request #11
Opened 2023-08-03 17:31 UTC by Valentan390

2023-08-03 22:04 UTC, guemplen commented on src/css/base/common.css
> +  font-family: 'DM Sans', sans-regular;
This file is shared, it cannot be modified or committed! The font has already been added to the main branch.

2023-08-03 22:07 UTC, guemplen commented on src/css/layout/we-will-call-you.css
> +  background-image: url(../../img/we-will-call-you/BG.png);
There is an extra dot in the path to the image file.

2023-08-03 22:07 UTC, guemplen commented on src/css/layout/we-will-call-you.css
> +    background-image: url(../../img/we-will-call-you/BG@2x.png);
There is an extra dot in the path to the image file.

2023-08-03 22:08 UTC, guemplen commented on src/css/layout/we-will-call-you.css
> +    background-image: url(../../img/we-will-call-you/BG-TAB.png);
There is an extra dot in the path to the image file.

2023-08-03 22:08 UTC, guemplen commented on src/css/layout/we-will-call-you.css
> +      background-image: url(../../img/we-will-call-you/BG-TAB@2x.png);
There is an extra dot in the path to the image file.

2023-08-03 22:08 UTC, guemplen commented on src/css/layout/we-will-call-you.css
> +    background-image: url(../../img/we-will-call-you/BG-desk.png);
There is an extra dot in the path to the image file.

2023-08-03 22:08 UTC, guemplen commented on src/css/layout/we-will-call-you.css
> +      background-image: url(../../img/we-will-call-you/BG-desk@2x.png);
There is an extra dot in the path to the image file.

2023-08-03 22:11 UTC, guemplen requested changes
Please, before making a pull request, commit only the files of your modules and images!!!

2023-08-04 10:07 UTC, Valentan390 commented
Удалил лишние точки

2023-08-04 10:17 UTC, closed without merging